#!/bin/bash
export PYTHONPATH=/home/ajmendez/dev/libs:/home/ajmendez/usr/local/lib/python2.7/site-packages
export PATH=/home/ajmendez/bin:$PATH
export DISPLAY=:99
echo '----'
date




# retry n times
n=0
until [ $n -ge 3 ]; do
    # casperjs ~/dev/bandwidth/tmobile/archive.js
    python ~/dev/bandwidth/tmobile/tmobile.py
    [  $? -eq 0 ] && break
    n=$[$n+1]
    sleep 10
done


# export PYTHONPATH=/home/ajmendez/dev/libs:/home/ajmendez/usr/local/lib/python2.7/site-packages
# python ~/dev/bandwidth/tmobile/parse.py